### ISSUE TITLE
Missing Firefox 104 release

### ISSUE THREAD

**Issue by d2s** [stefanjudis/browsers.fyi#5]
On the current https://www.browsers.fyi/ website ("Rebuilt September 1, 2022"), last visible Firefox release is from July:

> "Firefox 103 was released July 26, 2022."

Even while the MDN data source's [`firefox.json`](https://github.com/mdn/browser-compat-data/blob/main/browsers/firefox.json) has more recent details:

```json
        "104": {
          "release_date": "2022-08-23",
          "release_notes": "https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/104",
          "status": "beta",
          "engine": "Gecko",
          "engine_version": "104"
        },
```

Looking closer, realized that the cause of issue is that data lists 104 as "beta", even while the planned release day has long gone past. Previous release is still there as "current", so the data quality issue is caused by MDN itself.

```json
        "103": {
          "release_date": "2022-07-26",
          "release_notes": "https://developer.mozilla.org/docs/Mozilla/Firefox/Releases/103",
          "status": "current",
          "engine": "Gecko",
          "engine_version": "103"
        },
```

Not sure what is the process they use for updating those details, but thought to write the notes.

**Comment by stefanjudis** [comment]
Thanks @d2s!

Yeah... That's the downside of the taken approach. I guess, it'll resolve itself once the MDN or Mozilla folks update the data. There's little to do about this other than PR'ing MDN. 

I'll close here, but thanks for the future note!
